name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coverage==5.5 coveragepy-lcov validate_docbr

      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml

      - name: Convert coverage to lcov
        run: |
          coveragepy-lcov < coverage.xml > coverage.lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov

